version: '3'

services:
    admin:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                project: admin
        ports:
        -   "4020:80"
        environment:
            - project=admin
