apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: raifhack-hpa
  namespace: raifhack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: raifhack-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10