apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: raifhack-ingress
  namespace: raifhack
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - host: "a8a60a5d0ba8.sn.mynetname.net"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: external-api-service 
            port: 
              number: 80
  - host: "localhost"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: external-api-service 
            port: 
              number: 80