apiVersion: v1
kind: Service
metadata:
  name: external-api-service 
  namespace: raifhack
spec:
  type: NodePort
  selector: 
    app: external-api-deployment
  ports: 
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP